/**
 * Industry taxonomy for the NSE universe.
 *
 * Three levels — industry, group, subgroup:
 *   sector (11, Yahoo) -> indGrp "industry" (~58, e.g. "Banks")
 *                      -> subGrp "subgroup" (~150, e.g. "Private Sector Bank")
 *
 * SUB_TO_GRP maps published subgroup ->
 * industry parentage (universe.json, 181 pairs, zero ambiguity), so every
 * subgroup name we emit resolves to exactly one industry.
 */

export const SUB_TO_GRP: Record<string, string> = {
  "2/3 Wheelers": "Automobiles",
  "Abrasives & Bearings": "Industrial Products",
  "Advertising & Media Agencies": "Media",
  "Aerospace & Defense": "Aerospace & Defense",
  "Airline": "Transport Services",
  "Airport & Airport services": "Transport Infrastructure",
  "Aluminium": "Non - Ferrous Metals",
  "Aluminium, Copper & Zinc Products": "Industrial Products",
  "Amusement Parks/ Other Recreation": "Leisure Services",
  "Animal Feed": "Food Products",
  "Asset Management Company": "Capital Markets",
  "Auto Components & Equipments": "Auto Components",
  "Auto Dealer": "Automobiles",
  "Biotechnology": "Pharmaceuticals & Biotechnology",
  "Breweries & Distilleries": "Beverages",
  "Business Process Outsourcing (BPO)/ Knowledge Process Outsourcing (KPO)": "Commercial Services & Supplies",
  "Cables - Electricals": "Industrial Products",
  "Carbon Black": "Chemicals & Petrochemicals",
  "Castings & Forgings": "Industrial Products",
  "Cement & Cement Products": "Cement & Cement Products",
  "Ceramics": "Consumer Durables",
  "Cigarettes & Tobacco Products": "Cigarettes & Tobacco Products",
  "Civil Construction": "Construction",
  "Coal": "Consumable Fuels",
  "Commercial Vehicles": "Agricultural, Commercial & Construction Vehicles",
  "Commodity Chemicals": "Chemicals & Petrochemicals",
  "Compressors, Pumps & Diesel Engines": "Industrial Products",
  "Computers - Software & Consulting": "IT - Software",
  "Computers Hardware & Equipments": "IT - Hardware",
  "Construction Vehicles": "Agricultural, Commercial & Construction Vehicles",
  "Consulting Services": "Commercial Services & Supplies",
  "Consumer Electronics": "Consumer Durables",
  "Copper": "Non - Ferrous Metals",
  "Dairy Products": "Food Products",
  "Dealers-Commercial Vehicles, Tractors, Construction Vehicles": "Agricultural, Commercial & Construction Vehicles",
  "Depositories, Clearing Houses and Other Intermediaries": "Capital Markets",
  "Digital Entertainment": "Entertainment",
  "Diversified": "Diversified",
  "Diversified Commercial Services": "Commercial Services & Supplies",
  "Diversified FMCG": "Diversified FMCG",
  "Diversified Metals": "Diversified Metals",
  "Diversified Retail": "Retailing",
  "Diversified consumer products": "Consumer Durables",
  "Dredging": "Engineering Services",
  "Dyes And Pigments": "Chemicals & Petrochemicals",
  "E-Learning": "Other Consumer Services",
  "E-Retail/ E-Commerce": "Retailing",
  "Edible Oil": "Agricultural Food & other Products",
  "Education": "Other Consumer Services",
  "Electrodes & Refractories": "Industrial Products",
  "Exchange and Data Platform": "Capital Markets",
  "Explosives": "Chemicals & Petrochemicals",
  "Ferro & Silica Manganese": "Ferrous Metals",
  "Fertilizers": "Fertilizers & Agrochemicals",
  "Film Production, Distribution & Exhibition": "Entertainment",
  "Financial Institution": "Finance",
  "Financial Products Distributor": "Capital Markets",
  "Financial Technology (Fintech)": "Financial Technology (Fintech)",
  "Footwear": "Consumer Durables",
  "Furniture, Home Furnishing": "Consumer Durables",
  "Garments & Apparels": "Textiles & Apparels",
  "Gas Transmission/Marketing": "Gas",
  "Gems, Jewellery And Watches": "Consumer Durables",
  "General Insurance": "Insurance",
  "Glass - Consumer": "Consumer Durables",
  "Glass - Industrial": "Industrial Products",
  "Granites & Marbles": "Consumer Durables",
  "Healthcare Research, Analytics & Technology": "Healthcare Services",
  "Healthcare Service Provider": "Healthcare Services",
  "Heavy Electrical Equipment": "Electrical Equipment",
  "Holding Company": "Finance",
  "Hospital": "Healthcare Services",
  "Hotels & Resorts": "Leisure Services",
  "Household Appliances": "Consumer Durables",
  "Household Products": "Household Products",
  "Houseware": "Consumer Durables",
  "Housing Finance Company": "Finance",
  "IT Enabled Services": "IT - Services",
  "Industrial Gases": "Chemicals & Petrochemicals",
  "Industrial Machinery": "Industrial Manufacturing",
  "Industrial Minerals": "Minerals & Mining",
  "Industrial Products": "Industrial Manufacturing",
  "Insurance Distributors": "Insurance",
  "Integrated Power Utilities": "Power",
  "Internet & Catalogue Retail": "Retailing",
  "Investment Company": "Finance",
  "Iron & Steel": "Ferrous Metals",
  "Iron & Steel Products": "Industrial Products",
  "Jute & Jute Products": "Paper, Forest & Jute Products",
  "LPG/CNG/PNG/LNG Supplier": "Gas",
  "Leather And Leather Products": "Consumer Durables",
  "Life Insurance": "Insurance",
  "Logistics Solution Provider": "Transport Services",
  "Lubricants": "Petroleum Products",
  "Meat Products including Poultry": "Food Products",
  "Media & Entertainment": "Entertainment",
  "Medical Equipment & Supplies": "Healthcare Equipment & Supplies",
  "Microfinance Institutions": "Finance",
  "Multi Utilities": "Other Utilities",
  "Non Banking Financial Company (NBFC)": "Finance",
  "Offshore Support Solution Drilling": "Oil",
  "Oil Equipment & Services": "Oil",
  "Oil Exploration & Production": "Oil",
  "Oil Storage & Transportation": "Oil",
  "Other Agricultural Products": "Agricultural Food & other Products",
  "Other Bank": "Banks",
  "Other Beverages": "Beverages",
  "Other Capital Market related Services": "Capital Markets",
  "Other Construction Materials": "Other Construction Materials",
  "Other Consumer Services": "Other Consumer Services",
  "Other Electrical Equipment": "Electrical Equipment",
  "Other Financial Services": "Finance",
  "Other Food Products": "Food Products",
  "Other Industrial Products": "Industrial Products",
  "Other Telecom Services": "Telecom - Services",
  "Other Textile Products": "Textiles & Apparels",
  "Packaged Foods": "Food Products",
  "Packaging": "Industrial Products",
  "Paints": "Consumer Durables",
  "Paper & Paper Products": "Paper, Forest & Jute Products",
  "Passenger Cars & Utility Vehicles": "Automobiles",
  "Personal Care": "Personal Products",
  "Pesticides & Agrochemicals": "Fertilizers & Agrochemicals",
  "Petrochemicals": "Chemicals & Petrochemicals",
  "Pharmaceuticals": "Pharmaceuticals & Biotechnology",
  "Pharmacy Retail": "Retailing",
  "Pig Iron": "Ferrous Metals",
  "Plastic Products - Consumer": "Consumer Durables",
  "Plastic Products - Industrial": "Industrial Products",
  "Plywood Boards/ Laminates": "Consumer Durables",
  "Port & Port services": "Transport Infrastructure",
  "Power - Transmission": "Power",
  "Power Distribution": "Power",
  "Power Generation": "Power",
  "Power Trading": "Power",
  "Precious Metals": "Non - Ferrous Metals",
  "Print Media": "Media",
  "Printing & Publication": "Printing & Publication",
  "Printing Inks": "Chemicals & Petrochemicals",
  "Private Sector Bank": "Banks",
  "Public Sector Bank": "Banks",
  "Railway Wagons": "Industrial Manufacturing",
  "Ratings": "Capital Markets",
  "Refineries & Marketing": "Petroleum Products",
  "Residential, Commercial Projects": "Realty",
  "Restaurants": "Leisure Services",
  "Road AssetsToll, Annuity, Hybrid-Annuity": "Transport Infrastructure",
  "Road Transport": "Transport Services",
  "Rubber": "Industrial Products",
  "Sanitary Ware": "Consumer Durables",
  "Seafood": "Food Products",
  "Ship Building & Allied Services": "Industrial Manufacturing",
  "Shipping": "Transport Services",
  "Software Products": "IT - Software",
  "Speciality Retail": "Retailing",
  "Specialty Chemicals": "Chemicals & Petrochemicals",
  "Sponge Iron": "Ferrous Metals",
  "Stationary": "Household Products",
  "Stockbroking & Allied": "Capital Markets",
  "Sugar": "Agricultural Food & other Products",
  "TV Broadcasting & Software Production": "Entertainment",
  "Tea & Coffee": "Agricultural Food & other Products",
  "Telecom -  Equipment & Accessories": "Telecom -  Equipment & Accessories",
  "Telecom - Cellular & Fixed line services": "Telecom - Services",
  "Telecom - Infrastructure": "Telecom - Services",
  "Tour, Travel Related Services": "Leisure Services",
  "Tractors": "Agricultural, Commercial & Construction Vehicles",
  "Trading & Distributors": "Commercial Services & Supplies",
  "Trading - Auto components": "Auto Components",
  "Trading - Chemicals": "Chemicals & Petrochemicals",
  "Trading - Gas": "Gas",
  "Trading - Metals": "Metals & Minerals Trading",
  "Trading - Minerals": "Metals & Minerals Trading",
  "Trading - Textile Products": "Textiles & Apparels",
  "Transport Related Services": "Transport Services",
  "Tyres & Rubber Products": "Auto Components",
  "Waste Management": "Other Utilities",
  "Water Supply & Management": "Other Utilities",
  "Web based media and service": "Media",
  "Wellness": "Leisure Services",
  "Zinc": "Non - Ferrous Metals",
};

/** Yahoo industry -> taxonomy subgroup (industry is derived via SUB_TO_GRP). */
export const YAHOO_SUB_MAP: Record<string, string> = {
  "Specialty Chemicals": "Specialty Chemicals",
  "Textile Manufacturing": "Other Textile Products",
  "Engineering & Construction": "Civil Construction",
  "Auto Parts": "Auto Components & Equipments",
  "Drug Manufacturers - Specialty & Generic": "Pharmaceuticals",
  "Steel": "Iron & Steel",
  "Specialty Industrial Machinery": "Industrial Machinery",
  "Capital Markets": "Stockbroking & Allied",
  "Information Technology Services": "IT Enabled Services",
  "Real Estate - Development": "Residential, Commercial Projects",
  "Credit Services": "Non Banking Financial Company (NBFC)",
  "Packaged Foods": "Packaged Foods",
  "Electrical Equipment & Parts": "Other Electrical Equipment",
  "Agricultural Inputs": "Fertilizers",
  "Chemicals": "Commodity Chemicals",
  "Software - Application": "Software Products",
  "Banks - Regional": "Private Sector Bank",
  "Building Products & Equipment": "Other Industrial Products",
  "Asset Management": "Asset Management Company",
  "Luxury Goods": "Gems, Jewellery And Watches",
  "Building Materials": "Other Construction Materials",
  "Packaging & Containers": "Packaging",
  "Conglomerates": "Diversified",
  "Furnishings, Fixtures & Appliances": "Household Appliances",
  "Lodging": "Hotels & Resorts",
  "Metal Fabrication": "Castings & Forgings",
  "Integrated Freight & Logistics": "Logistics Solution Provider",
  "Apparel Manufacturing": "Garments & Apparels",
  "Entertainment": "Film Production, Distribution & Exhibition",
  "Farm Products": "Other Agricultural Products",
  "Confectioners": "Packaged Foods",
  "Medical Care Facilities": "Hospital",
  "Real Estate Services": "Residential, Commercial Projects",
  "Paper & Paper Products": "Paper & Paper Products",
  "Education & Training Services": "Education",
  "Solar": "Power Generation",
  "Specialty Business Services": "Diversified Commercial Services",
  "Aerospace & Defense": "Aerospace & Defense",
  "Communication Equipment": "Telecom -  Equipment & Accessories",
  "Footwear & Accessories": "Footwear",
  "Household & Personal Products": "Personal Care",
  "Farm & Heavy Construction Machinery": "Construction Vehicles",
  "Auto Manufacturers": "Passenger Cars & Utility Vehicles",
  "Mortgage Finance": "Housing Finance Company",
  "Software - Infrastructure": "Software Products",
  "Telecom Services": "Telecom - Cellular & Fixed line services",
  "Drug Manufacturers - General": "Pharmaceuticals",
  "Infrastructure Operations": "Port & Port services",
  "Oil & Gas Refining & Marketing": "Refineries & Marketing",
  "Other Industrial Metals & Mining": "Aluminium, Copper & Zinc Products",
  "Utilities - Independent Power Producers": "Power Generation",
  "Apparel Retail": "Speciality Retail",
  "Biotechnology": "Biotechnology",
  "Tools & Accessories": "Abrasives & Bearings",
  "Utilities - Renewable": "Power Generation",
  "Beverages - Wineries & Distilleries": "Breweries & Distilleries",
  "Broadcasting": "TV Broadcasting & Software Production",
  "Aluminum": "Aluminium",
  "Marine Shipping": "Shipping",
  "Publishing": "Print Media",
  "Oil & Gas Equipment & Services": "Oil Equipment & Services",
  "Real Estate - Diversified": "Residential, Commercial Projects",
  "Restaurants": "Restaurants",
  "Diagnostics & Research": "Healthcare Research, Analytics & Technology",
  "Insurance - Life": "Life Insurance",
  "Internet Retail": "E-Retail/ E-Commerce",
  "Department Stores": "Diversified Retail",
  "Electronic Components": "Computers Hardware & Equipments",
  "Financial Conglomerates": "Other Financial Services",
  "Utilities - Regulated Electric": "Power Distribution",
  "Utilities - Regulated Gas": "Gas Transmission/Marketing",
  "Advertising Agencies": "Advertising & Media Agencies",
  "Electronics & Computer Distribution": "Trading & Distributors",
  "Lumber & Wood Production": "Plywood Boards/ Laminates",
  "Medical Instruments & Supplies": "Medical Equipment & Supplies",
  "Thermal Coal": "Coal",
  "Business Equipment & Supplies": "Stationary",
  "Copper": "Copper",
  "Industrial Distribution": "Trading & Distributors",
  "Railroads": "Railway Wagons",
  "Tobacco": "Cigarettes & Tobacco Products",
  "Travel Services": "Tour, Travel Related Services",
  "Waste Management": "Waste Management",
  "Consumer Electronics": "Consumer Electronics",
  "Financial Data & Stock Exchanges": "Exchange and Data Platform",
  "Food Distribution": "Trading & Distributors",
  "Health Information Services": "Healthcare Research, Analytics & Technology",
  "Oil & Gas E&P": "Oil Exploration & Production",
  "Rental & Leasing Services": "Diversified Commercial Services",
  "Shell Companies": "Holding Company",
  "Specialty Retail": "Speciality Retail",
  "Staffing & Employment Services": "Business Process Outsourcing (BPO)/ Knowledge Process Outsourcing (KPO)",
  "Airports & Air Services": "Airport & Airport services",
  "Auto & Truck Dealerships": "Auto Dealer",
  "Computer Hardware": "Computers Hardware & Equipments",
  "Consulting Services": "Consulting Services",
  "Internet Content & Information": "Web based media and service",
  "Leisure": "Amusement Parks/ Other Recreation",
  "Medical Devices": "Medical Equipment & Supplies",
  "Trucking": "Road Transport",
  "Beverages - Non-Alcoholic": "Other Beverages",
  "Pharmaceutical Retailers": "Pharmacy Retail",
  "Resorts & Casinos": "Hotels & Resorts",
  "Scientific & Technical Instruments": "Other Industrial Products",
  "Beverages - Brewers": "Breweries & Distilleries",
  "Home Improvement Retail": "Speciality Retail",
  "Insurance - Diversified": "General Insurance",
  "Insurance Brokers": "Insurance Distributors",
  "Oil & Gas Integrated": "Oil Exploration & Production",
  "Pollution & Treatment Controls": "Water Supply & Management",
  "Security & Protection Services": "Diversified Commercial Services",
  "Semiconductors": "Computers Hardware & Equipments",
  "Airlines": "Airline",
  "Coking Coal": "Coal",
  "Discount Stores": "Diversified Retail",
  "Electronic Gaming & Multimedia": "Digital Entertainment",
  "Gold": "Precious Metals",
  "Grocery Stores": "Diversified Retail",
  "Healthcare Plans": "General Insurance",
  "Insurance - Property & Casualty": "General Insurance",
  "Insurance - Reinsurance": "General Insurance",
  "Medical Distribution": "Medical Equipment & Supplies",
  "Oil & Gas Drilling": "Offshore Support Solution Drilling",
  "Other Precious Metals & Mining": "Precious Metals",
  "Semiconductor Equipment & Materials": "Computers Hardware & Equipments",
  "Utilities - Regulated Water": "Water Supply & Management",
};
